/* Regenerate the README images from a running instance.
 *
 * Committed images go stale silently, so they are generated by a script that
 * anyone can re-run rather than captured by hand. Run `make e2e` servers or
 * point BASE_URL and API at a live pair.
 */
import { chromium } from "@playwright/test";
import { mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..", "docs", "images");
const BASE = process.env.BASE_URL ?? "http://localhost:3031";
mkdirSync(OUT, { recursive: true });

const SHOTS = [
  { route: "/", name: "season-night", theme: "Night", width: 1440 },
  { route: "/forecast", name: "forecast-night", theme: "Night", width: 1440 },
  { route: "/measure", name: "measure-day", theme: "Day", width: 1440 },
  { route: "/creatives", name: "creatives-night", theme: "Night", width: 1440 },
  { route: "/compliance", name: "compliance-day", theme: "Day", width: 1440 },
  { route: "/plan", name: "plan-night", theme: "Night", width: 1440 },
  { route: "/data", name: "data-night", theme: "Night", width: 1440 },
  { route: "/brand", name: "brand-day", theme: "Day", width: 1440 },
  { route: "/security", name: "security-night", theme: "Night", width: 1440 },
  { route: "/", name: "season-mobile", theme: "Night", width: 390 },
];

const b = await chromium.launch();
for (const s of SHOTS) {
  const p = await b.newPage({ viewport: { width: s.width, height: 1000 }, deviceScaleFactor: 2 });
  await p.goto(BASE + s.route, { waitUntil: "networkidle" });
  await p.getByRole("button", { name: s.theme, exact: true }).click();
  await p.waitForTimeout(700);
  await p.screenshot({ path: join(OUT, `${s.name}.png`), fullPage: true });
  console.log(`  ${s.name}.png`);
  await p.close();
}
await b.close();
