"""The label that cannot be dropped.

UPLIFT forecasts against a footfall series that does not exist: there is no
public hourly footfall data for any Dubai cafe, and inventing one is the only
way to demonstrate the method. That is defensible. What would not be defensible
is a chart, an API response or a report sentence that carried those numbers
without saying where they came from.

So `simulated` is not a convention here — it is a constructor invariant. A
record that does not declare itself simulated cannot be built, the database
column is NOT NULL with a CHECK constraint, and both are covered by tests. The
label survives every join, every serialisation and every copy-paste, because
there is no code path that produces one of these without it.
"""

from __future__ import annotations

from dataclasses import dataclass


class NotLabelledError(ValueError):
    """Raised when a generated record is constructed without its label."""


@dataclass(frozen=True)
class FootfallRecord:
    """One zone-hour of generated footfall."""

    zone_code: str
    ts_local: str
    footfall: int
    transactions: int
    simulated: bool = True

    def __post_init__(self) -> None:
        if self.simulated is not True:
            raise NotLabelledError(
                "footfall is generated by pipeline/footfall.py and has no observed "
                "counterpart; a record claiming otherwise would misrepresent the "
                "one thing this project must not misrepresent"
            )
        if self.footfall < 0 or self.transactions < 0:
            raise ValueError("footfall and transactions cannot be negative")
        if self.transactions > self.footfall:
            raise ValueError(
                f"{self.zone_code} {self.ts_local}: {self.transactions} transactions from "
                f"{self.footfall} visitors — conversion above 1.0 is not a rounding error"
            )

    def as_row(self) -> tuple:
        return (self.zone_code, self.ts_local, self.footfall, self.transactions, 1)


@dataclass(frozen=True)
class BasketRecord:
    """One point-of-sale basket in the sample export."""

    basket_id: str
    customer_id: str
    zone_code: str
    ts_local: str
    items: int
    amount_aed: float
    daypart: str
    sample: bool = True

    def __post_init__(self) -> None:
        if self.sample is not True:
            raise NotLabelledError(
                "this basket comes from a generated sample export, not from a till"
            )
        if self.items < 1 or self.amount_aed <= 0:
            raise ValueError("a basket has at least one item and a positive value")

    def as_row(self) -> tuple:
        return (
            self.basket_id,
            self.customer_id,
            self.zone_code,
            self.ts_local,
            self.items,
            self.amount_aed,
            self.daypart,
            1,
        )
