"""Creatives, compliance verdicts and panel scores.

Everything here is deterministic and read-only. No creative is published, sent
or scheduled by this API — exporting a campaign is a human action taken
somewhere else, and there is no endpoint that could do it.
"""

from __future__ import annotations

from fastapi import APIRouter, HTTPException, Query

from services.api.creative import compliance, panel
from services.api.creative.compose import COPY, LANGS, SIZES, all_creatives, compose

router = APIRouter(prefix="/creative", tags=["creative"])


def _payload(slot: str, lang: str, size: str) -> dict:
    c = compose(slot, lang, size)
    v = compliance.check(c.text, c)
    p = panel.score(c)
    return {
        "slot": c.slot,
        "lang": c.lang,
        "size": c.size,
        "width": c.width,
        "height": c.height,
        "seed": c.seed,
        "zone": c.zone,
        "daypart": c.daypart,
        "product": c.product,
        "headline": c.headline,
        "body": c.body,
        "cta": c.cta,
        "svg": c.svg,
        "compliance": {
            "passed": v.passed,
            "checked_rules": v.checked_rules,
            "citations": v.citations,
            "findings": [
                {
                    "rule_id": f.rule_id,
                    "family": f.family,
                    "severity": f.severity,
                    "matched": f.matched,
                    "why": f.why,
                    "source_code": f.source_code,
                    "source_title": f.source_title,
                    "source_url": f.source_url,
                    "clause": f.clause,
                    "clause_verified": f.clause_verified,
                    "clause_quote": f.clause_quote,
                }
                for f in v.findings
            ],
        },
        "panel": {
            "mean": p.mean,
            "spread": p.spread,
            "scores": [
                {
                    "persona": s.persona,
                    "name": s.name,
                    "total": s.total,
                    "criteria": s.criteria,
                    "note": s.note,
                }
                for s in p.scores
            ],
            "simulated": True,
        },
    }


@router.get("/slots", summary="Every creative slot, language and size")
def slots() -> dict:
    return {
        "slots": sorted(COPY),
        "languages": list(LANGS),
        "sizes": {k: list(v) for k, v in SIZES.items()},
        "deterministic": True,
        "note": (
            "Creatives are composed from data/brand/sidra.yaml rather than generated by "
            "an image service. Free image endpoints rate-limit unpredictably and garble "
            "Arabic inside images, which in an application about brand compliance is a "
            "liability rather than a shortcut — and a panel score is only meaningful if "
            "the artefact it scores is stable under a seed."
        ),
    }


@router.get("/all", summary="Every variant with its verdict and panel score")
def every(size: str = Query("square")) -> dict:
    if size not in SIZES:
        raise HTTPException(404, f"no size {size!r}; have {sorted(SIZES)}")
    items = [_payload(c.slot, c.lang, size) for c in all_creatives(size)]
    return {
        "count": len(items),
        "creatives": items,
        "passing": sum(1 for i in items if i["compliance"]["passed"]),
        "deterministic": True,
    }


@router.get("/{slot}", summary="One variant")
def one(slot: str, lang: str = Query("en"), size: str = Query("square")) -> dict:
    if slot not in COPY:
        raise HTTPException(404, f"no slot {slot!r}; have {sorted(COPY)}")
    if lang not in LANGS:
        raise HTTPException(404, f"no language {lang!r}")
    if size not in SIZES:
        raise HTTPException(404, f"no size {size!r}")
    return _payload(slot, lang, size)


compliance_router = APIRouter(prefix="/compliance", tags=["compliance"])


@compliance_router.get("/rules", summary="The rule set, with its sources")
def rules() -> dict:
    from services.api.brand import load_brand

    brand = load_brand()
    return {
        "rules": [
            {
                "id": r.id,
                "family": r.family,
                "severity": r.severity,
                "patterns": list(r.patterns),
                "rule_type": r.rule_type,
                "why": r.why.strip(),
                "source": brand.sources[r.source].citation(),
                "source_url": brand.sources[r.source].url,
                "clause": r.clause,
                "clause_verified": r.clause_verified,
                "clause_quote": r.clause_quote,
            }
            for r in brand.claims_to_avoid
        ],
        "sources": {k: v.citation() for k, v in brand.sources.items()},
        "deterministic": True,
        "note": (
            "Matching is regex over NFKC-normalised text. A rule engine whose verdict "
            "depends on a model's mood cannot be audited, and the claim this "
            "application makes is that every verdict cites the clause it came from."
        ),
    }


@compliance_router.get("/gold", summary="Recall and precision on the 40-case gold set")
def gold() -> dict:
    return {**compliance.evaluate_gold(), "target_recall": 0.90}


# A GET, not a POST. It computes a verdict from a string and stores nothing, so
# there is no state change to model — and making it a POST left the API with one
# mutating-looking route while CORS allowed GET alone, which would have failed
# the moment the Compliance tab called it from a browser. The whole API is now
# GET, which is both a simpler claim and a true one.
@compliance_router.get("/check", summary="Check arbitrary copy")
def check_text(text: str = Query(..., min_length=1, max_length=2000)) -> dict:
    v = compliance.check(text)
    return {
        "text": text,
        "passed": v.passed,
        "checked_rules": v.checked_rules,
        "findings": [
            {
                "rule_id": f.rule_id,
                "severity": f.severity,
                "matched": f.matched,
                "why": f.why,
                "source_code": f.source_code,
                "clause": f.clause,
                "clause_verified": f.clause_verified,
            }
            for f in v.findings
        ],
    }
